# ATTENTION: 
# This file is generated, do not edit this file manually!
# If you need to change the version, do so in the project.toml, e.g. by using `poetry version X.Y.Z`.

MAJOR = 2
MINOR = 4
PATCH = 0

VERSION = f"{MAJOR}.{MINOR}.{PATCH}"
