name: Merge-Gate-Extension
on: workflow_call

jobs:
  approve-run-merge-gate-extension:
    name: Approve Running Merge Gate Extension?
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    environment: manual-approval
    steps:
      - name: Tests
        run: echo "Merge Gate Extension approved"

  verify-examples:
    name: Verify examples
    needs: [ approve-run-merge-gate-extension ]
    uses: ./.github/workflows/verify-examples.yml
    permissions:
      contents: read
