name: Slow-Checks

on:
  workflow_call:

jobs:
  build-matrix:
    name: Build Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["connectors", "exasol_versions", "integration_group", "python_versions"]'
    permissions:
      contents: read

  run-integration-tests:
    name: Integration-Tests (Python-${{ matrix.python_versions }}, test:${{ matrix.integration_group }}, Exasol-${{ matrix.exasol_versions}}, ${{matrix.connectors}})
    needs:
      - build-matrix
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Check out Repository
        id: check-out-repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up Python & Poetry Environment
        id: set-up-python-and-poetry-environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v10
        with:
          python-version: ${{ matrix.python_versions }}
          poetry-version: "2.3.0"

      - name: Start Test DB
        id: start-test-db
        run: poetry run -- nox -s db:start -- --db-version ${MATRIX_EXASOL_VERSIONS}
        env:
          MATRIX_EXASOL_VERSIONS: ${{ matrix.exasol_versions }}

      - name: Run Integration Tests
        id: run-integration-tests
        run: poetry run -- nox -s test:${MATRIX_INTEGRATION_GROUP}
        env:
          MATRIX_INTEGRATION_GROUP: ${{ matrix.integration_group }}

      - name: Upload Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v7
        with:
          name: coverage-python${{ matrix.python_versions }}-${{ matrix.integration_group }}-exasol${{ matrix.exasol_versions }}-${{matrix.connectors}}-slow
          path: .coverage
          include-hidden-files: true
          overwrite: false

      - name: Stop Test DB
        id: stop-test-db
        run: poetry run -- nox -s db:stop
