name: Verify examples

on:
  workflow_call:

jobs:
  build-matrix:
    name: Build Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["exasol_versions", "minimum_python_version"]'
    permissions:
      contents: read

  verify-examples:
    name: Verify Examples (Python-${{ matrix.minimum_python_version }}, Exasol-${{ matrix.exasol_versions}})
    needs: [ build-matrix ]
    runs-on:  "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v10
        with:
          python-version: ${{ matrix.minimum_python_version }}

      - name: Start test db
        run: poetry run -- nox -s db:start -- --db-version ${MATRIX_EXASOL_VERSIONS}
        env:
          MATRIX_EXASOL_VERSIONS: ${{ matrix.exasol_versions }}

      - name: Run examples
        run: poetry run -- nox -s run:examples
        env:
          PYTHONPATH: .

      - name: Stop test db
        run: poetry run -- nox -s db:stop
